[MeterStylePrimaryThin]
AntiAlias=1
FontFace=#FontPrimaryThin#

[MeterStylePrimaryLight]
AntiAlias=1
FontFace=#FontPrimaryLight#

[MeterStylePrimary]
AntiAlias=1
FontFace=#FontPrimary#

[MeterStylePrimaryMedium]
AntiAlias=1
FontFace=#FontPrimaryMedium#

[MeterStylePrimaryBold]
AntiAlias=1
FontFace=#FontPrimaryBold#

[MeterStyleTitle]
AntiAlias=1
FontFace=#FontTitle#

[MeterStyleTitleBold]
AntiAlias=1
FontFace=#FontTitleBold#

[MeterStyleMono]
AntiAlias=1
FontFace=#FontMono#

[MeterStyleIdentifier]
AntiAlias=1
FontFace=#FontIdentifier#

[MeterStyleIdentifierBold]
AntiAlias=1
FontFace=#FontIdentifierBold#
