[MeterDividerFooter]
Meter=Shape
X=#PanelPaddingX#
Y=#DividerFooterY#
Shape=#DividerFooterShape# | Fill Color #ColorNeutralStrokeSecondary# | StrokeWidth 0

[MeterFooterMark]
AntiAlias=1
PreserveAspectRatio=1
Meter=Image
X=#FooterMarkX#
Y=#FooterMarkY#
ImageName=#@#Assets\#Footermark#
W=#FooterMarkSize#
H=#FooterMarkSize#

[MeterFooterName]
Meter=String
X=#FooterNameX#
Y=#FooterNameY#
Text=#FooterName#
MeterStyle=MeterStylePrimaryBold
FontSize=#FooterNameSize#
FontColor=#ColorNeutralForegroundPrimary#

[MeterFooterChinese]
Meter=String
StringAlign=LeftBottom
X=#FooterChineseX#
Y=#FooterChineseY#
Text=#FooterChinese#
MeterStyle=MeterStylePrimary
FontSize=#FooterNameChineseSize#
FontColor=#ColorNeutralForegroundPrimary#

[MeterFooterTagline]
Meter=String
StringAlign=Right
X=#FooterTaglineX#
Y=#FooterTaglineY#
Text=#FooterTagline#
FontSize=#FooterTagLineSize#
MeterStyle=MeterStyleMono
FontColor=#ColorNeutralForegroundSecondary#


[MeterFooterCode]
Meter=String
X=#FooterCodex#
Y=#FooterCodeY#
Text=#FooterCode#
FontSize=#FooterCodeSize#
MeterStyle=MeterStyleIdentifierBold
FontColor=#ColorNeutralForegroundSecondary#

[MeterFooterBarsBrand]
TrailingSpaces=1
Meter=String
StringAlign=Right
X=#FooterBarsBrandX#
Y=#FooterBarsBrandY#
Text=#FooterBarsBrand#
FontSize=#FooterBarsBrandSize#
MeterStyle=MeterStyleTitleBold
FontColor=#ColorBrandForeground#

[MeterFooterBarsNeutral]
TrailingSpaces=1
Meter=String
StringAlign=Right
X=#FooterBarsNeutralX#
Y=#FooterBarsNeutralY#
Text=#FooterBarsNeutral#
FontSize=#FooterBarsNeutralSize#
MeterStyle=MeterStyleTitleBold
FontColor=#ColorNeutralForeground#
