[Variables]
; Encode: UTF-16 LE with BOM
; Header
HeaderNodeCode=HUB-DESK / 001
HeaderMark=Logos\Star.png
DateCJKTimeLabel=%1月%2日 %3
DateTimeLabel=%1,  %2 %3

; QuickAccess
DeskTitle=Basalt Desk
DeskSubTitle=Local Access Terminal

SectionTitle=快速访问   /   Quick Access
ItemArrow=›

Item1Title=工作区
Item1Subtitle=Workspace
Item1Icon=Icons\Workspace.png
Item1Arrow=›
Item1Path=C:\Users\Lenovo\AppData\Roaming\Microsoft\Windows\Libraries\Workspace.library-ms

Item2Title=收件箱
Item2Subtitle=Inbox
Item2Icon=Icons\Inbox.png
Item2Arrow=›
Item2Path=C:\Users\Lenovo\AppData\Roaming\Microsoft\Windows\Libraries\Inbox.library-ms

Item3Title=学业
Item3Subtitle=Academics
Item3Icon=Icons\Academics.png
Item3Arrow=›
Item3Path=C:\Users\Lenovo\AppData\Roaming\Microsoft\Windows\Libraries\Academics.library-ms

Item4Title=创作
Item4Subtitle=Studio
Item4Icon=Icons\Studio.png
Item4Arrow=›
Item4Path=

Item5Title=个人
Item5Subtitle=Personal
Item5Icon=Icons\Personal.png
Item5Arrow=›
Item5Path=

Item6Title=保管库
Item6Subtitle=Vault
Item6Icon=Icons\Vault.png
Item6Arrow=›
Item6Path=

; Footer
Footermark=Logos\Main.png

FooterBarsBrand="////    "
FooterBarsNeutral="  //"
FooterTagLine=We Chart The PATH.#CRLF#We Build The Future.#CRLF#We Are One.
FooterName=StarTrack#CRLF#Confederation
FooterChinese=星轨联合政府
FooterCode=ICT-Fj$ESXZ{C0DHa+%J-lVΩRG