[MeterStyleCardTitle]
AntiAlias=1
FontSize=#TileItemTitleSize#
FontColor=#ColorNeutralForegroundSecondary#
FontFace=#FontPrimaryMedium#

[MeterStyleCardSubtitle]
AntiAlias=1
FontSize=#TileItemSubtitleSize#
FontColor=#ColorNeutralForegroundSecondary#
FontFace=#FontPrimary#

[MeterStyleCardArrow]
AntiAlias=1
MeterStyle=MeterStylePrimary
FontSize=#TileItemArrowSize#
FontColor=#Accent#
StringAlign=Right
